/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ndktest_MyLog */

#ifndef _Included_com_android_ndktest_MyLog
#define _Included_com_android_ndktest_MyLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ndktest_MyLog
 * Method:    HelloLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ndktest_MyLog_HelloLog
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
