/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ndktest_MyCpp */

#ifndef _Included_com_android_ndktest_MyCpp
#define _Included_com_android_ndktest_MyCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ndktest_MyCpp
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_ndktest_MyCpp_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
