/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ndktest_MyNDK */

#ifndef _Included_com_android_ndktest_MyNDK
#define _Included_com_android_ndktest_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    Hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_ndktest_MyNDK_Hello
  (JNIEnv *, jclass);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloIntegerAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_android_ndktest_MyNDK_HelloIntegerAdd
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloIntegerSubtract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_android_ndktest_MyNDK_HelloIntegerSubtract
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloIntegerMultiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_android_ndktest_MyNDK_HelloIntegerMultiply
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloIntegerDivide
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_android_ndktest_MyNDK_HelloIntegerDivide
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloDoubleAdd
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_android_ndktest_MyNDK_HelloDoubleAdd
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloDoubleSubtract
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_android_ndktest_MyNDK_HelloDoubleSubtract
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloDoubleMultiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_android_ndktest_MyNDK_HelloDoubleMultiply
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloDoubleDivide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_android_ndktest_MyNDK_HelloDoubleDivide
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_ndktest_MyNDK_HelloBoolean
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloStringSprint
 * Signature: (Ljava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_ndktest_MyNDK_HelloStringSprint
  (JNIEnv *, jclass, jstring, jdouble);

/*
 * Class:     com_android_ndktest_MyNDK
 * Method:    HelloDoubleArray
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_android_ndktest_MyNDK_HelloDoubleArray
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
