/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ndktest_Employee */

#ifndef _Included_com_android_ndktest_Employee
#define _Included_com_android_ndktest_Employee
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ndktest_Employee
 * Method:    raiseSalary
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_android_ndktest_Employee_raiseSalary
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
